### PR TITLE
Remove deps cached only when deps in mix file changed

### LINKED ISSUE #235: Formatting does not work with phoenix and neovim (with vim-lsp)
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.10.2 (compiled with Erlang/OTP 22)
* ElixirLS version: v0.3.3
* Operating system: macOS
* Editor or IDE name (e.g. Emacs/VSCode): neovim with vim-lsp
* Phoenix version: v1.4.16

### Description 

The bug happens when I generate phoenix project. After I open file inside project and try formatting with `LspDocumentFormat`. `vim-lsp` returns an errors (described in Reproduce Steps below).

### Reproduce Steps

- Create project with `mix phx.new --no-html --no-webpack --no-gettext lsp_formatter` and fetch and install dependencies.
- Open `lib/lsp_formatter.ex` with `nvim`. Waiting elixir-ls to compile.
- Call  `LspDocumentFormat`, received an error that capture from vim lsp log: 

```
Thu May  7 23:35:24 2020:["--->", 3, "elixir-ls", {"method": "textDocument/formatting", "on_notification": "---funcref---", "sync": 0, "params": {"options": {"insertSpaces": true, "tabSize"
: 2}, "textDocument": {"uri": "file:///Users/thanabodee/src/github.com/wingyplus/lsp_formatter/lib/lsp_formatter.ex"}}}]
Thu May  7 23:35:24 2020:["<---", 3, "elixir-ls", {"response": {"id": 2, "jsonrpc": "2.0", "error": {"code": -32000, "message": "an exception was raised:\n    ** (Mix.Error) Unknown depende
ncy :ecto_sql given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :test\n        (mix 1.10.2) lib/mix.ex:392: Mix.raise/1\n
     (mix 1.10.2) lib/mix/tasks/format.ex:246: anonymous fn/3 in Mix.Tasks.Format.eval_deps_opts/2\n        (elixir 1.10.2) lib/enum.ex:2111: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n
(mix 1.10.2) lib/mix/tasks/format.ex:245: Mix.Tasks.Format.eval_deps_opts/2\n        (mix 1.10.2) lib/mix/tasks/format.ex:201: anonymous fn/5 in Mix.Tasks.Format.eval_deps_and_subdirectories/4\n        (mix 1.10.2) lib/mix/tasks/format.ex:276: anonymous fn/2 in Mix.Tasks.Format.eval_subs_opts/3\n        (elixir 1.10.2) lib/enum.ex:1094: anonymous fn/3 in Enum.flat_map_reduce/
3\n        (elixir 1.10.2) lib/enum.ex:3686: Enumerable.List.reduce/3"}}, "request": {"id": 2, "jsonrpc": "2.0", "method": "textDocument/formatting", "params": {"options": {"insertSpaces":
true, "tabSize": 2}, "textDocument": {"uri": "file:///Users/thanabodee/src/github.com/wingyplus/lsp_formatter/lib/lsp_formatter.ex"}}}}]
Thu May  7 23:35:24 2020:["<---", 3, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "\n23:35:24.508 [error] Process #PID<0.4583.0> raised
an exception\n** (Mix.Error) Unknown dependency :ecto_sql given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :test\n    (mix
1.10.2) lib/mix.ex:392: Mix.raise/1\n    (mix 1.10.2) lib/mix/tasks/format.ex:246: anonymous fn/3 in Mix.Tasks.Format.eval_deps_opts/2\n    (elixir 1.10.2) lib/enum.ex:2111: Enum.\"-reduce/
3-lists^foldl/2-0-\"/3\n    (mix 1.10.2) lib/mix/tasks/format.ex:245: Mix.Tasks.Format.eval_deps_opts/2\n    (mix 1.10.2) lib/mix/tasks/format.ex:201: anonymous fn/5 in Mix.Tasks.Format.eva
l_deps_and_subdirectories/4\n    (mix 1.10.2) lib/mix/tasks/format.ex:276: anonymous fn/2 in Mix.Tasks.Format.eval_subs_opts/3\n    (elixir 1.10.2) lib/enum.ex:1094: anonymous fn/3 in Enum.
flat_map_reduce/3\n    (elixir 1.10.2) lib/enum.ex:3686: Enumerable.List.reduce/3", "type": 4}}}]
```

- Try comment `subdirectories` in `.formatter.exs`:

```
[
  import_deps: [:ecto, :phoenix],
  inputs: ["*.{ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs}"],
  # subdirectories: ["priv/*/migrations"]
]
```

- Restart editor (open the same file) and try formatting. It received the same kind of errors but different lib (previously, it's :ecto_sql. the current is :ecto)

```
Thu May  7 23:38:07 2020:["--->", 3, "elixir-ls", {"method": "textDocument/formatting", "on_notification": "---funcref---", "sync": 0, "params": {"options": {"insertSpaces": true, "tabSize"
: 2}, "textDocument": {"uri": "file:///Users/thanabodee/src/github.com/wingyplus/lsp_formatter/lib/lsp_formatter.ex"}}}]
Thu May  7 23:38:07 2020:["<---", 3, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "[ElixirLS Dialyzer] Done writing manifest in 1561 mil
liseconds.", "type": 3}}}]
Thu May  7 23:38:08 2020:["<---", 3, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "[ElixirLS WorkspaceSymbols] Indexing...", "type": 3}}
}]
Thu May  7 23:38:08 2020:["<---", 3, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "Compiling with Mix env test", "type": 4}}}]
Thu May  7 23:38:08 2020:["<---", 3, "elixir-ls", {"response": {"id": 2, "jsonrpc": "2.0", "error": {"code": -32000, "message": "an exception was raised:\n    ** (Mix.Error) Unknown depende
ncy :ecto given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :test\n        (mix 1.10.2) lib/mix.ex:392: Mix.raise/1\n
 (mix 1.10.2) lib/mix/tasks/format.ex:246: anonymous fn/3 in Mix.Tasks.Format.eval_deps_opts/2\n        (elixir 1.10.2) lib/enum.ex:2111: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n        (mix
 1.10.2) lib/mix/tasks/format.ex:245: Mix.Tasks.Format.eval_deps_opts/2\n        (mix 1.10.2) lib/mix/tasks/format.ex:201: anonymous fn/5 in Mix.Tasks.Format.eval_deps_and_subdirectories/4\
n        (mix 1.10.2) lib/mix/tasks/format.ex:160: Mix.Tasks.Format.formatter_opts_for_file/2\n        (language_server 0.3.3) lib/language_server/providers/formatting.ex:12: ElixirLS.Langu
ageServer.Providers.Formatting.format/3\n        (language_server 0.3.3) lib/language_server/server.ex:535: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2"}}, "requ
est": {"id": 2, "jsonrpc": "2.0", "method": "textDocument/formatting", "params": {"options": {"insertSpaces": true, "tabSize": 2}, "textDocument": {"uri": "file:///Users/thanabodee/src/gith
ub.com/wingyplus/lsp_formatter/lib/lsp_formatter.ex"}}}}]
Thu May  7 23:38:08 2020:["<---", 3, "elixir-ls", {"response": {"method": "window/logMessage", "jsonrpc": "2.0", "params": {"message": "\n23:38:08.864 [error] Process #PID<0.285.0> raised a
n exception\n** (Mix.Error) Unknown dependency :ecto given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :test\n    (mix 1.10.
2) lib/mix.ex:392: Mix.raise/1\n    (mix 1.10.2) lib/mix/tasks/format.ex:246: anonymous fn/3 in Mix.Tasks.Format.eval_deps_opts/2\n    (elixir 1.10.2) lib/enum.ex:2111: Enum.\"-reduce/3-lis
ts^foldl/2-0-\"/3\n    (mix 1.10.2) lib/mix/tasks/format.ex:245: Mix.Tasks.Format.eval_deps_opts/2\n    (mix 1.10.2) lib/mix/tasks/format.ex:201: anonymous fn/5 in Mix.Tasks.Format.eval_dep
s_and_subdirectories/4\n    (mix 1.10.2) lib/mix/tasks/format.ex:160: Mix.Tasks.Format.formatter_opts_for_file/2\n    (language_server 0.3.3) lib/language_server/providers/formatting.ex:12:
 ElixirLS.LanguageServer.Providers.Formatting.format/3\n    (language_server 0.3.3) lib/language_server/server.ex:535: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/
2", "type": 4}}}]
```

- Next step, try to comment `import_deps` in `.formatter.exs`: 

```
[
  # import_deps: [:ecto, :phoenix],
  inputs: ["*.{ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs}"],
  # subdirectories: ["priv/*/migrations"]
]
```

- Restart editor and try formatting. It's works!! :tada:

### More information 

I try it with vscode without any comments in `.formatter.exs`. It's works fine.
Run `mix format`. It's works fine.

### PR DESCRIPTION
**Pull request by wingyplus**
Remove deps cached every build can cause deps cached disappear in :ets.
Fixes by move calling Mix.Project.clear_deps_cache/0 only when deps in
mix.exs was change.

Fixes #235

### CODE REVIEW

File: apps/language_server/lib/language_server/build.ex [hunk 1]
```diff
@@ -20,15 +20,14 @@ defmodule ElixirLS.LanguageServer.Build do
...
-              :ok = Mix.Project.clear_deps_cache()
-
               case reload_project() do
                 {:ok, mixfile_diagnostics} ->
                   # FIXME: Private API
                   if Keyword.get(opts, :fetch_deps?) and
-                       Mix.Dep.load_on_environment([]) != prev_deps,
-                     do: fetch_deps()
+                       Mix.Dep.load_on_environment([]) != cached_deps() do
+                    :ok = Mix.Project.clear_deps_cache()
```
Comment (axelson) [inline apps/language_server/lib/language_server/build.ex:28]: Can we add an explanatory comment about why this needs to be within the if statement?

**Comment by lukaszsamson** [comment]
It looks reasonable but TBH I don't know this code very well

File: apps/language_server/lib/language_server/build.ex (hunk 1 above)
Comment (wingyplus) [reply apps/language_server/lib/language_server/build.ex:30]: @axelson NOTE comment added.

**Comment by wingyplus** [comment]
@axelson @lukaszsamson To be honest, I don't understand the reason why we need to clear deps cache every time  before fetching deps. :D

**Comment by wingyplus** [comment]
It's seems test was failing at dialyzer again. oTZ

**Comment by axelson** [comment]
@wingyplus the test output (some of that debugger issue) was improved in https://github.com/elixir-lsp/elixir-ls/pull/347 and if I can clean up https://github.com/elixir-lsp/elixir-ls/pull/352 the test suite can become green again. So we don't need to worry about it for this PR. I plan to do a bit more testing on this and get it merged soon, hopefully this weekend, but if I take longer feel free to ping me.

**Comment by wingyplus** [comment]
@axelson That's ok. What can I help?

**Comment by axelson** [comment]
Thanks for rebasing! Merging now.
