### PR TITLE
Use elixir 1.15 `:root` in formatter_for

### LINKED ISSUE #526: Formatter doesn't respect formatter.exs while your code is still compiling
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.11.3 (compiled with Erlang/OTP 21)

* VSCode ElixirLS version: 0.7.0
* Operating System Version: darwin 20.3.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

https://www.dropbox.com/s/llgnf7ham9d0hf8/Screen%20Recording%202021-04-07%20at%208.28.49%20AM.mov?dl=0

You can reproduce this by deleting the `.elixir_ls` directory, and then saving a file to trigger the LS to start recompiling, then run the formatter. You observe that it is not respecting the formatter configuration because it is adding parens to Ecto functions/macros that shouldn't have parens.

The screen recording I added above using VSCode, but I have also reproduced it with Neovim builtin language client.

I personally have never run into this race condition, but my coworkers constantly are pushing up code that is clearly formatted incorrectly, and I traced it down to this issue.

Thanks!

### PR DESCRIPTION
**Pull request by DianaOlympos**
fix #526 on elixir 1.15+. see https://github.com/elixir-lang/elixir/pull/12541

I am not a fan of the tests. I was not sure what to add. Everything passes locally but... eh

On the experimental side, I moved to version checking as @lukaszsamson asked. I did not touch the logic on the rest of the file.

Happy to do changes if you prefer.

### CODE REVIEW

File: apps/language_server/lib/language_server/experimental/code_mod/format.ex [hunk 1]
```diff
@@ -44,15 +44,21 @@ defmodule ElixirLS.LanguageServer.Experimental.CodeMod.Format do
...
           {:ok, formatter_function, keyword()} | {:error, :no_formatter_available}
-  defp formatter_for(uri_or_path) do
+  defp formatter_for(uri_or_path, project_dir) do
     path = Conversions.ensure_path(uri_or_path)
 
     try do
       true = Code.ensure_loaded?(Mix.Tasks.Format)
 
-      if function_exported?(Mix.Tasks.Format, :formatter_for_file, 1) do
+      if project_dir && Version.match?(System.version(), ">= 1.15.0") do
```
Comment (lukaszsamson) [inline apps/language_server/lib/language_server/experimental/code_mod/format.ex:55]: we can use `-dev` or `-rc.0` for now to make testing easier

**Review by lukaszsamson — APPROVED** [review]

File: apps/language_server/lib/language_server/experimental/code_mod/format.ex (hunk 1 above)
Comment (DianaOlympos) [reply apps/language_server/lib/language_server/experimental/code_mod/format.ex]: done
