### PR TITLE
Ensure build is complete before finishing tests

### LINKED ISSUE #495: Race conditions on CI
```
==> language_server
304
Compiling 53 files (.ex)
305
Generated language_server app
306
Excluding tags: [pending: true]
307

308
.................................................................................................................................
309
Error: 9.758 [error] Process #PID<0.1995.0> raised an exception
310
** (ErlangError) Erlang error: :terminated
311
    (stdlib 3.8.2.4) :io.put_chars(:standard_io, :unicode, ["\n== Compilation error in file lib/language_server/providers/code_lens/type_spec.ex ==\n", ["** (MatchError) no match of right hand side value: {:error, :enoent}", 10, "    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7\n"]])
312
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:557: Kernel.ParallelCompiler.wait_for_messages/7
313
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:149: Kernel.ParallelCompiler.spawn_workers/3
314
    (mix 1.11.3) lib/mix/compilers/elixir.ex:94: Mix.Compilers.Elixir.compile/6
315
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
316
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
317
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
318
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
319
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
320
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
321
    (mix 1.11.3) lib/mix/tasks/compile.ex:119: Mix.Tasks.Compile.run/1
322
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
323
    (language_server 0.6.5) lib/language_server/build.ex:199: ElixirLS.LanguageServer.Build.compile/0
324
    (language_server 0.6.5) lib/language_server/build.ex:29: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
325
    (stdlib 3.8.2.4) timer.erl:166: :timer.tc/1
326
    (language_server 0.6.5) lib/language_server/build.ex:12: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
327
    (kernel 6.3.1.3) global.erl:430: :global.trans/4
328
................................................................................................................Content-Length: 192
329

330
{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"Building core Dialyzer Elixir PLT. This will take a few minutes (often 15+) and can be disabled in the settings.","type":3}}Content-Length: 151
331

332
{"jsonrpc":"2.0","method":"window/showMessage","params":{"message":"Saved Elixir PLT to /home/runner/.mix/elixir-ls-21.3.8.20_elixir-1.11.3","type":3}}
333
Error: 2.144 [error] Task #PID<0.1650.2> started from #PID<0.1336.2> terminating
334
** (ArgumentError) argument error
335
    (stdlib 3.8.2.4) :ets.select_trap({#Reference<0.3124882355.642383874.196698>, 3490, 0, #Reference<0.3124882355.642383874.200898>, [
```

### PR DESCRIPTION
**Pull request by lukaszsamson**
Fixes #495

### CODE REVIEW

File: apps/language_server/test/server_test.exs [hunk 1]
```diff
@@ -937,6 +937,8 @@ defmodule ElixirLS.LanguageServer.ServerTest do
 
       # File is already formatted
       assert response(3, []) == resp
+
+      wait_until_compiled(server)
```
Comment (axelson) [inline apps/language_server/test/server_test.exs:941]: Instead of adding these to each individual test directly, could we add it to a generic setup block? Perhaps one that checks for `fixture: true`. That would make it harder to miss one of these in the future.

Comment (lukaszsamson) [reply apps/language_server/test/server_test.exs:941]: I tried adding it in `on_exit` callback but the server process is already down when it's executed. We'd need wrapping it in a lambda or macro with `do` block.

Comment (axelson) [reply apps/language_server/test/server_test.exs:941]: Ah, k.

**Review by axelson — APPROVED** [review]
:heart:
