### PR TITLE
Make wrapper script more robust... more robustly

### LINKED ISSUE #470: Latest changes to language_server.sh break startup on macOS
### Environment

* Elixir & Erlang versions (elixir --version): Elixir `1.11.3` & Erlang `23.2.3`
* Operating system: macOS `10.15.7`
* Editor or IDE name (e.g. Emacs/VSCode): Sublime Text `3.2.2`
* Editor Plugin/LSP Client name: `LSP-elixir`

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

---

Hey everyone, it seems your [recent changes to language_server.sh](https://github.com/elixir-lsp/elixir-ls/commit/843e1a6cc964df82f604be94d0784773205758f3) broke something on macOS. If I revert those changes everything works fine again.

See [sublimelsp/LSP-elixir#14](https://github.com/sublimelsp/LSP-elixir/issues/14) for details.

### PR DESCRIPTION
**Pull request by jtrees**
This makes a setup possible in which a symlink points to the file (e.g. /usr/local/bin/elixir-ls -> /opt/elixir-ls/language_server.sh).

It's a rehash of a previous PR (#445) that was reverted since it broke setups where the language server was installed in a path containing spaces (e.g. /opt/Elixir Language Server/). This variant takes that possibility into account.

Hopefully, this fixes #470.

### CODE REVIEW

File: apps/elixir_ls_utils/priv/language_server.sh [hunk 1]
```diff
@@ -1,7 +1,17 @@
 #!/bin/sh
 # Launches the language server. This script must be in the same directory as the compiled .ez archives.
 
-dir=$(dirname "$0")
+readlink_f () {
+  cd "$(dirname "$1")" > /dev/null
```
Comment (lukaszsamson) [inline apps/elixir_ls_utils/priv/language_server.sh:5]:
```suggestion
  cd "$(dirname "$1")" > /dev/null || exit 1
```

**Comment by lukaszsamson** [comment]
We would need a similar change in debugger.sh
This PR currently conflicts with https://github.com/elixir-lsp/elixir-ls/pull/467

File: apps/elixir_ls_utils/priv/language_server.sh (hunk 1 above)
Comment (jtrees) [reply apps/elixir_ls_utils/priv/language_server.sh:5]: Good idea!

**Comment by jtrees** [comment]
Hmmm... Are you still interested in this change? #467 offers an alternative to solve this issue. The specific use-case of using a symlink (as addressed in this PR) still wouldn't work but alternatively the `language_server.sh` could be moved to a different location (as long as `$ELS_INSTALL_PREFIX` is set).

**Comment by axelson** [comment]
@jtrees I think it would be nice to include, although I'm not sure how common using a symlink like this is. But I would generally expect a symlink to work so it would be nice to support it.

**Review by lukaszsamson — APPROVED** [review]

**Review by axelson — APPROVED** [review]
:heart: Thanks for fixing this up :+1:
