### PR TITLE
fix: remove assumption to fix deterministic builds

### LINKED ISSUE #1197: Fails to start on Elixir deterministic build
```
Running /home/linh/.vscode/extensions/jakebecker.elixir-ls-0.28.0/elixir-ls-release/launch.sh
Preferred shell is zsh, relaunching
Looking for asdf install
asdf not found
Looking for mise executable
mise not found
Looking for rtx executable
rtx not found
Looking for vfox executable
vfox not found
Installing ElixirLS release v0.28.0
Running in /home/linh/sandbox/rap
Install complete
[Info  - 07:30:17] Started ElixirLS v0.28.0
[Info  - 07:30:17] Running in /home/linh/sandbox/rap
[Info  - 07:30:17] ElixirLS built with elixir "1.18.4" on OTP "27"
[Info  - 07:30:17] Running on elixir "1.18.4 (compiled with Erlang/OTP 27)" on OTP "27"
[Info  - 07:30:17] Protocols are not consolidated
[Warn  - 07:30:17] ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1    
    
    The following arguments were given to IO.chardata_to_string/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 2 out of 2):
    
        def chardata_to_string(+string+) when -is_binary(string)-
        def chardata_to_string(+list+) when -is_list(list)-
    
    (elixir 1.18.4) lib/io.ex:710: IO.chardata_to_string/1
    (elixir 1.18.4) lib/file.ex:246: File.exists?/2
    (language_server 0.28.0) lib/language_server.ex:146: ElixirLS.LanguageServer.check_elixir_sources/0
    (language_server 0.28.0) lib/language_server.ex:63: ElixirLS.LanguageServer.main/0
    /home/linh/.vscode/extensions/jakebecker.elixir-ls-0.28.0/elixir-ls-release/launch.exs:18: (file)
    (elixir 1.18.4) lib/code.ex:1525: Code.require_file/2
[Error - 07:30:17] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 07:30:17] The ElixirLS - rap server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 07:30:17] ElixirLS - rap client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 07:30:17] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 07:30:17] Server process exited with code 1.
``
```

### PR DESCRIPTION
**Pull request by soupglasses**
Current code has an assumption that `[:compile][:source]` will always exist in the output of `Enum.module_info()`. This is stripped from Elixir's deterministic build toggle
(`ERL_COMPILER_OPTIONS=deterministic`).

Added an assumption for `~"/"` as a fallback when such a case happens to keep the old logging behaviour. This can be changed as seen fit.

Manual testing shows that elixir-ls will no longer throw on startup due to `nil` given as a path with a deterministic build of Elixir.

Fixes #1197

### CODE REVIEW

File: apps/language_server/lib/language_server.ex [hunk 1]
```diff
@@ -143,8 +143,9 @@ defmodule ElixirLS.LanguageServer do
     enum_ex_path = Enum.module_info()[:compile][:source]
 
     elixir_sources_available =
-      unless File.exists?(enum_ex_path, [:raw]) do
-        dir = Path.join(enum_ex_path, "../../../..") |> Path.expand()
+      # handle possible nil from deterministic build of elixir
+      unless enum_ex_path && File.exists?(enum_ex_path, [:raw]) do
+        dir = Path.join(enum_ex_path || ~c"/", "../../../..") |> Path.expand()
```
Comment (Munksgaard) [inline apps/language_server/lib/language_server.ex:148]: This seems wrong? If enum_ex_path is nil, this will return... "/../../.."?

Comment (soupglasses) [reply apps/language_server/lib/language_server.ex:148]: The `Path.expand()` will collapse it down to `/`, so the log message shows `"Elixir sources not found (checking in /). Code navigation to Elixir modules disabled."`

Main reasoning for this was to avoid changing the behavior for the output logging for the case of elixir deterministic build where source has been stripped.

This entire block is fragile, as the previous logged output would have been `/home/abuild/rpmbuild/BUILD/elixir-1.18.4-build/elixir-1.18.4` under openSUSE Tumbleweed. Which would have been equally strange, since this is an artifact from the build system, and not a path you'd ever see on a user's system.

Comment (Munksgaard) [reply apps/language_server/lib/language_server.ex:148]: Got it.

Comment (Munksgaard) [reply apps/language_server/lib/language_server.ex]: Thanks. I was confused by it when I read it :D
