### PR TITLE
Fix Formatting.format returns character float number

### LINKED ISSUE #249: vim-lsp cannot format due to character in position is float type
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Editor: neovim + vim-lsp
* Operating system: macOS
* ElixirLS version: 0.4.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

### Logs

Consider this example:

```
defmodule LspFormattingBug do
  @moduledoc """
  Documentation for `LspFormattingBug`.
  """

  @doc """
  Hello world.

  ## Examples

      iex> LspFormattingBug.hello()
      :world

  """
     def hello do
    :world
  end
end
```

The `def hello` is incorrect indent. So I called `textDocument/formatting` and got an error from vim-lsp:

```
Mon May 18 10:01:21 2020:["--->", 3, "elixir-ls", {"method": "textDocument/formatting", "on_notification": "---funcref---", "sync": 0, "params": {"options": {"insertSpaces": true, "tabSize": 2
}, "textDocument": {"uri": "file:///Users/thanabodee/src/github.com/wingyplus/lsp_formatting_bug/lib/lsp_formatting_bug.ex"}}}]
Mon May 18 10:01:21 2020:["<---", 3, "elixir-ls", {"response": {"id": 5, "jsonrpc": "2.0", "result": [{"range": {"end": {"character": 5.0, "line": 14}, "start": {"character": 2.0, "line": 14}}, "newText": ""}]}, "request": {"id": 5, "jsonrpc": "2.0", "method": "textDocument/formatting", "params": {"options": {"insertSpaces": true, "tabSize": 2}, "textDocument": {"uri": "file:///Use
rs/thanabodee/src/github.com/wingyplus/lsp_formatting_bug/lib/lsp_formatting_bug.ex"}}}}]
Mon May 18 10:01:21 2020:["s:on_stdout client request on_notification() error", "Vim(let):E805: Using a Float as a Number", "function <SNR>88_on_stdout[4]..<SNR>87_on_stdout[79]..<lambda>74[1]..<SNR>101_handle_text_edit[10]..lsp#utils#text_edit#apply_text_edits[7]..<SNR>102__apply, line 4"]
```

I think this happens because character convert to float after `byte_size(..) / 2`. Use `Kernel.trunc/1` might solve this issue.

### PR DESCRIPTION
**Pull request by wingyplus**
This bug happens because of use `/ 2` in advance_pos which is convert
into floating number. Fixes by using `trunc/1`. And add test to ensure
line and character always integer.

Fixes #249

### CODE REVIEW

File: apps/language_server/lib/language_server/providers/formatting.ex [hunk 1]
```diff
@@ -81,7 +81,7 @@ defmodule ElixirLS.LanguageServer.Providers.Formatting do
       else
         # LSP contentChanges positions are based on UTF-16 string representation
         # https://microsoft.github.io/language-server-protocol/specification#textDocuments
-        {line, col + byte_size(:unicode.characters_to_binary(char, :utf8, :utf16)) / 2}
+        {line, col + trunc(byte_size(:unicode.characters_to_binary(char, :utf8, :utf16)) / 2)}
```
Comment (axelson) [inline apps/language_server/lib/language_server/providers/formatting.ex:84]: Can you change this to use `Kernel.div/2` instead?

**Comment by wingyplus** [comment]
@axelson your suggestion was addressed. CI fail because of dialyzer test. I think this is not related with this changes.

**Comment by x-ji** [comment]
Didn't see the issue you opened and this PR before I opened mine (with Emacs)... https://github.com/elixir-lsp/elixir-ls/issues/255 https://github.com/elixir-lsp/elixir-ls/pull/256 Could somebody ensure that the pipeline is rerun and the fix for the bug is merged. Thanks.

**Comment by wingyplus** [comment]
@x-ji commit was squash and ci are all green.
